config/routes.rb
Rails.application.routes.draw do
    #devise_for :users

   root 'pages#homepage'
  resources :products, only: %i[index show edit destroy new create update destroy]
  resources :warehouses, only: %i[index show edit new create update destroy] do
    resources :stocks, only: %i[create]
  end
  resources :orders, only: %i[index show edit new create update destroy] do
    resources :order_items, only: %i[create destroy]
  end
end
#don't nest more than thrice

app/views/shared/_flash.html.erb
<% if flash[:notice] || flash[:alert] %>
  <div class="alert alert-<%= flash[:notice].present? ? 'success' : 'danger' %>">
    <%= flash[:notice] || flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark navbar-expand-md">
  <div class="container">
    <%= link_to "Inventory", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-target="#navbar-content">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if user_signed_in? %>
    <div class="collapse navbar-collapse justify-content-space-between" id="navbar-content">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Products", products_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Warehouse", warehouses_path, class: "nav-link" %>
        </li>
      
        <li class="nav-item">
          <%= link_to "Orders", orders_path, class: "nav-link" %>
        </li>
      </ul>
      <% else %>
        <div class="text-white">
          INVENTORY SYSTEM BRODIES
        </div>
      <% end %>
        <div class="text-white">
          <% if user_signed_in? %>
            Hi there, <%= current_user.email %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger"%>
          <% else %>
            <%= link_to "Sign in", user_session_path, class: "btn btn-success" %>
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-primary" %>
          <% end %>
        </div>
    </div>
  </div>
</nav>