config/routes.rb
Rails.application.routes.draw do
    #devise_for :users

   root 'pages#homepage'
  resources :products, only: %i[index show edit destroy new create update destroy]
  resources :warehouses, only: %i[index show edit new create update destroy] do
    resources :stocks, only: %i[create]
  end
  resources :orders, only: %i[index show edit new create update destroy] do
    resources :order_items, only: %i[create destroy]
  end
end
#don't nest more than thrice

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :warehouse
  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items

  validates :customer_name, presence: true


  before_validation :assign_uuid


private

def assign_uuid
    return unless new_record? || uuid.empty?
    generated_uuid = ''
    presence = true
    while presence == true
      generated_uuid = SecureRandom.uuid
      presence = false unless Order.exists?(uuid: generated_uuid)
    end
    self.uuid = generated_uuid
  end
end

app/controllers/orders_controller.rb
class OrdersController < AdminController
  before_action :set_order, only: %i[show edit update destroy]

  def index
    @orders = Order.all
  end

  def show
    @order_items = @order.order_items
    @order_item = @order.order_items.build
    @products = Product.all
  end

  def new
    @order = Order.new
    @warehouses = Warehouse.all
  end

  def create
    @order = Order.new(order_params)

    if @order.save
      flash.notice = 'Successfully created order.'

      redirect_to order_path(@order)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @order.update(order_params)
      flash.notice = 'Successfully updated order.'

      redirect_to order_path(@order)
    else
      render :edit
    end
  end

  def destroy
    @order.destroy!
    flash.notice = 'Successfully deleted order.'

    redirect_to orders_path
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:warehouse_id, :customer_name)
  end
end

app/views/orders/index.html.erb
<div class="container">
   <h1>Orders</h1>
  <%= link_to "New Order", new_order_path, class: "btn btn-primary" %>
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Customer Name</th>
        <th>Warehouse</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.id %></td>
          <td><%= order.customer_name %></td>
          <td><%= order.warehouse.full_address %></td>
          <td>
            <%= link_to "Show", order_path(order) %>
           
            <%= link_to "Delete", order_path(order), method: :delete %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/orders/new.html.erb
<div class="container">
  <h2>New Order</h2>
  <%= render "form", order: @order, warehouses: @warehouses %>
</div>

app/views/orders/order.html.erb
<%= form_with model: order, local: true, id: "new_order_form" do |f| %>
  <div class="form-group">
    <%= f.label :customer_name %>
    <%= f.text_field :customer_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :warehouse %>
    <%= f.select :warehouse_id, warehouses.map { |warehouse|
      [warehouse.full_address, warehouse.id] }, {}, { class: "form-control"} %>
  </div>
  <%= f.submit "Save Order", class: "btn btn-success", id: "submit-button" %>
<% end %>

app/views/orders/show.html.erb
<div class="container">
  <h2>Order (ID: <%= @order.id %>)</h2>
  <small>Customer</small>

  <h4><%= @order.customer_name %></h4>
  <small>Warehouse</small>

  <h4><%= @order.warehouse.full_address %></h4>

  <%= render "order_items/form",
    order_item: @order_item,
    products: @products,
    order: @order %>

    <br>

  <table class = "table">
    <thead>
      <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @order_items.each do |order_item| %>
        <% next if order_item.new_record? %>
        <tr>
          <td><%= order_item.product.name %></td>
          <td><%= order_item.quantity %></td>
          <td><%= link_to "Delete", order_order_item_path(@order, order_item), method: :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>