config/routes.rb
Rails.application.routes.draw do
    #devise_for :users

   root 'pages#homepage'
  resources :products, only: %i[index show edit destroy new create update destroy]
  resources :warehouses, only: %i[index show edit new create update destroy] do
    resources :stocks, only: %i[create]
  end
  resources :orders, only: %i[index show edit new create update destroy] do
    resources :order_items, only: %i[create destroy]
  end
end
#don't nest more than thrice

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/controllers/order_items_controller.rb
class OrderItemsController < AdminController
  before_action :set_order

  def create
    @order_item = @order.order_items.find_or_initialize_by(product_id: order_items_params[:product_id].to_i)
    if @order_item.new_record?
      flash.notice = "Successfully added order item!"

      @order_item.quantity = order_items_params[:quantity].to_i
    else
      flash.notice = "Successfully added order item!"
      @order_item.quantity += order_items_params[:quantity].to_i
    end

    @order_item.save!

    redirect_to order_path(@order)
  end
end
  def destroy
    OrderItem.find(params[:id]).destroy!

    flash.notice = "Successfully deleted order item."

    redirect_to order_path(@order)
  end


  private

  def set_order
    @order = Order.find(params[:order_id])
  end

  def order_items_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

app/views/order_items/_form.html.erb
<%= form_with model: order_item, local: true, id: "order_item_form", class: "form-inline", url: order_order_items_path(order) do |f| %>
  <div class="form-group">
    <%= f.label :product %>
    <%= f.select :product_id, products.map { |p| [p.name, p.id] }, {}, { class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= f.label :quantity %>
    <%= f.number_field :quantity, class: "form-control",  required: true  %>
  </div>
  <%= f.submit "Add Order Item", class: "btn btn-success" %>
<% end %>